kind = "design"
previewPath = "/"
title = "Canvas"
version = "1.0.0"
id = "XegfDyZt7HqfW2Bb8Ghoy"

[[services]]
localPort = 8081
name = "Component Preview Server"
paths = ["/"]

[services.env]
PORT = "8081"
BASE_PATH = "/"

[services.development]
run = "pnpm --filter @workspace/mockup-sandbox run dev"

[services.production]

[services.production.build]
args = ["pnpm", "--filter", "@workspace/mockup-sandbox", "run", "build"]

[services.production.build.env]
PORT = "8081"
BASE_PATH = "/"
NODE_ENV = "production"

[services.production.run]
args = ["pnpm", "--filter", "@workspace/mockup-sandbox", "run", "preview"]

[services.production.run.env]
PORT = "8081"
BASE_PATH = "/"
NODE_ENV = "production"
