/** Auto-generated by scripts/extract-use-case-scenarios.mjs — do not edit by hand */
import type { ExampleScenario } from "@/components/UseCaseLayout";

export type LandingUseCaseScenario = {
  id: string;
  href: string;
  tagAr: string;
  titleAr: string;
  tagEn: string;
  titleEn: string;
  scenario: ExampleScenario;
  scenarioEn: ExampleScenario;
};

export const landingUseCaseScenarios: LandingUseCaseScenario[] = [
  {
    id: "AddToCartPage",
    href: "/use-cases/add-to-cart",
    tagAr: "حسب الأنشطة",
    titleAr: "إضافة للسلة",
    tagEn: "By Activity",
    titleEn: "Add to Cart",
    scenario: {
    title: "عميلة أضافت فاونديشن لسلتها",
    steps: [
      "العميلة اختارت فاونديشن بـ 110 ⃁ وضغطت 'أضف للسلة'.",
      "رصد زيادة اللحظة وعرض فوراً: 'عميلات اشترين هذا الفاونديشن اشترين أيضاً برايمر التثبيت بـ 55 ⃁'.",
      "ظهر العرض بتصميم Glassmorphism أنيق لا يقاطع التجربة — زر واحد 'أضف للسلة'.",
      "العميلة أضافت البرايمر بنقرة واحدة لأنه منطقي ومكمّل لما اشترته.",
    ],
    result: "قيمة الطلب ارتفعت من 110 إلى 165 ⃁ بقرار شراء لم تخطط له العميلة — لكنها سعيدة به.",
  },
    scenarioEn: {
    title: "A customer added foundation to her cart",
    steps: [
      "The customer chose foundation at 110 SAR and clicked 'Add to Cart'.",
      "Ziadah detected the moment and instantly showed: 'Customers who bought this foundation also bought setting primer at 55 SAR'.",
      "The offer appeared in an elegant glassmorphism design that doesn't interrupt the experience — one button: 'Add to Cart'.",
      "The customer added the primer with one click because it's logical and complements what she bought.",
    ],
    result: "Order value rose from 110 to 165 SAR with a purchase decision the customer didn't plan — but she's happy about it.",
  },
  },
  {
    id: "Addons",
    href: "/use-cases/addons",
    tagAr: "حسب طريقة العرض",
    titleAr: "الإضافات (Add-ons)",
    tagEn: "By Display Method",
    titleEn: "Add-ons",
    scenario: {
    title: "أمثلة من قطاعات متنوعة",
    steps: [
      "📱 إلكترونيات: عميل يضيف هاتف للسلة → تظهر قائمة: [✓] غلاف حماية +39 ⃁، [✓] واقي شاشة +15 ⃁، [ ] سماعة لاسلكية +89 ⃁ — يختار ويرى الإجمالي يتحدث.",
      "🌿 عناية: عميلة تشتري شامبو → تُعرض إضافات: [✓] بلسم مكمل +28 ⃁، [ ] ماسك أسبوعي +45 ⃁، [✓] سيروم تقوية +62 ⃁.",
      "🎮 ألعاب: عميل يشتري جهاز تحكم → يرى: [✓] حقيبة حمل +35 ⃁، [✓] بطاريات شحن +29 ⃁، [ ] غطاء زلق مانع +19 ⃁.",
      "🍕 مطعم: عميل يطلب بيتزا → يختار من: [✓] صوص إضافي +6 ⃁، [✓] حافة جبن +12 ⃁، [ ] مشروب +15 ⃁.",
    ],
    result: "الاختبار المتعدد يرفع متوسط عدد الإضافات المختارة من 0.7 إضافة (اقتراح واحد فقط) إلى 2.3 إضافة — ثلاثة أضعاف المبيعات الإضافية بنفس الجهد.",
  },
    scenarioEn: {
    title: "Examples from various industries",
    steps: [
      "📱 Electronics: Customer adds a phone to cart → list appears: [✓] Protective case +39 SAR, [✓] Screen protector +15 SAR, [ ] Wireless earbuds +89 SAR — they select and see the total update.",
      "🌿 Haircare: Customer buys shampoo → add-ons shown: [✓] Matching conditioner +28 SAR, [ ] Weekly mask +45 SAR, [✓] Strengthening serum +62 SAR.",
      "🎮 Gaming: Customer buys a controller → sees: [✓] Carrying case +35 SAR, [✓] Rechargeable batteries +29 SAR, [ ] Anti-slip grip cover +19 SAR.",
      "🍕 Restaurant: Customer orders pizza → selects from: [✓] Extra sauce +6 SAR, [✓] Cheese crust +12 SAR, [ ] Drink +15 SAR.",
    ],
    result: "Multi-select increases the average number of add-ons selected from 0.7 (single suggestion) to 2.3 — three times the additional sales with the same effort.",
  },
  },
  {
    id: "AllPages",
    href: "/use-cases/all-pages",
    tagAr: "حسب الصفحات",
    titleAr: "جميع الصفحات",
    tagEn: "By Pages",
    titleEn: "All Pages",
    scenario: {
    title: "رحلة عميل كاملة مع زيادة",
    steps: [
      "يدخل العميل الصفحة الرئيسية: يرى عروضاً مبنية على آخر زيارة له.",
      "ينتقل لتصنيف العناية: يجد ترتيباً ذكياً يضع أنسب المنتجات في المقدمة.",
      "يفتح صفحة منتج: يرى حزمة روتين كاملة كومبو بتوفير 20%.",
      "يضيف للسلة: يظهر له 'أضف 25 ⃁ للشحن المجاني' فيضيف منتجاً صغيراً.",
      "بعد الشراء: صفحة شكر بكوبون 15% لطلبه القادم خلال 48 ساعة.",
    ],
    result: "قيمة الطلب ارتفعت 55% مقارنة بالنية الأصلية، والعميل عاد خلال 36 ساعة باستخدام الكوبون.",
  },
    scenarioEn: {
    title: "A complete customer journey with Ziadah",
    steps: [
      "The customer enters the home page: sees offers built on their last visit.",
      "Moves to the skincare category: finds smart ordering placing the most relevant products up front.",
      "Opens a product page: sees a complete routine combo bundle with 20% savings.",
      "Adds to cart: shown 'Add 25 SAR for free shipping' so they add a small product.",
      "After purchase: a thank you page with a 15% coupon for their next order within 48 hours.",
    ],
    result: "Order value increased 55% compared to original intent, and the customer returned within 36 hours using the coupon.",
  },
  },
  {
    id: "BundleDeals",
    href: "/use-cases/bundle-deals",
    tagAr: "حسب طريقة العرض",
    titleAr: "عروض الحزم",
    tagEn: "By Display Method",
    titleEn: "Bundle Deals",
    scenario: {
    title: "أمثلة تطبيقية من قطاعات متنوعة",
    steps: [
      "💄 تجميل: حزمة 'روتين الصباح' = غسول + سيروم + مرطب بـ 199 ⃁ بدلاً من 249 ⃁ (توفير 50 ⃁) — عرض واضح يقنع بالقيمة.",
      "💻 إلكترونيات: حزمة 'الإنتاجية' = لابتوب + ماوس + حقيبة بـ 1899 ⃁ بدلاً من 2150 ⃁ — التوفير الكبير يُبرر القرار الفوري.",
      "🍔 مطعم: وجبة عائلية = 4 برغر + 4 مشروبات + بطاطس كبيرة بـ 119 ⃁ بدلاً من 148 ⃁ — يُناسب قرارات العائلة السريعة.",
      "🧴 رعاية شعر: حزمة 'شعر صحي' = شامبو + بلسم + ماسك أسبوعي بـ 89 ⃁ بدلاً من 112 ⃁ — توفير 23 ⃁ يُقنع العميلة بالطقم الكامل.",
    ],
    result: "العميل الذي يرى التوفير بوضوح (المبلغ وليس النسبة فقط) يتحول إلى المشتري بنسبة 52% — الشفافية في الخصم هي المحرك الأقوى لقرار الشراء.",
  },
    scenarioEn: {
    title: "Real examples from various industries",
    steps: [
      "💄 Beauty: 'Morning Routine' bundle = cleanser + serum + moisturizer at 199 SAR instead of 249 SAR (save 50 SAR) — a clear offer that convinces with value.",
      "💻 Electronics: 'Productivity' bundle = laptop + mouse + bag at 1,899 SAR instead of 2,150 SAR — the big saving justifies an immediate decision.",
      "🍔 Restaurant: Family meal = 4 burgers + 4 drinks + large fries at 119 SAR instead of 148 SAR — suits quick family decisions.",
      "🧴 Haircare: 'Healthy Hair' bundle = shampoo + conditioner + weekly mask at 89 SAR instead of 112 SAR — saving 23 SAR convinces the customer to get the full set.",
    ],
    result: "The customer who sees savings clearly (the amount, not just the percentage) converts at 52% — transparency in the discount is the strongest driver of purchase decisions.",
  },
  },
  {
    id: "BuyMoreSaveMore",
    href: "/use-cases/buy-more-save-more",
    tagAr: "حسب الأهداف",
    titleAr: "عروض الكميات",
    tagEn: "By Goals",
    titleEn: "Quantity Offers",
    scenario: {
    title: "أمثلة تطبيقية من قطاعات متنوعة",
    steps: [
      "☕ بن وقهوة: كيس قهوة 250 غ = 49 ⃁ / كيسين = 89 ⃁ (توفير 9 ⃁) / 3 أكياس = 119 ⃁ (توفير 28 ⃁) — شريط يُظهر 'أضف كيساً واحداً أكثر لتوفير 28 ⃁'.",
      "🧴 منظفات منزلية: منظف ليتر = 22 ⃁ / 3 عبوات = 19 ⃁ للعبوة / 6 عبوات = 16 ⃁ للعبوة — جدول شرائح واضح بجانب المنتج.",
      "💊 مكملات غذائية: علبة بروتين = 149 ⃁ / علبتان = 139 ⃁ لكل علبة / 3 علب = 125 ⃁ لكل علبة — مع توضيح 'كفاية 3 أشهر بسعر أشهر إضافية'.",
      "🖊️ قرطاسية: قلم = 8 ⃁ / عبوة 6 أقلام = 42 ⃁ (توفير 6 ⃁) / علبة 12 قلم = 72 ⃁ (توفير 24 ⃁) — خيارات الكمية بأزرار واضحة.",
    ],
    result: "عرض شريط التقدم 'أضف قطعة واحدة ووفّر X ⃁' يرفع معدل اختيار الكميات الأكبر بنسبة 42% مقارنة بجدول الشرائح الثابت — الرسالة الشخصية المباشرة تُحفّز أكثر.",
  },
    scenarioEn: {
    title: "Real examples from various industries",
    steps: [
      "☕ Coffee: 250g bag = 49 SAR / 2 bags = 89 SAR (save 9 SAR) / 3 bags = 119 SAR (save 28 SAR) — a bar shows 'Add one more bag to save 28 SAR'.",
      "🧴 Cleaning supplies: 1L cleaner = 22 SAR / 3 bottles = 19 SAR each / 6 bottles = 16 SAR each — a clear tier table beside the product.",
      "💊 Supplements: Protein box = 149 SAR / 2 boxes = 139 SAR each / 3 boxes = 125 SAR each — with a note: '3-month supply at the price of extra months'.",
      "🖊️ Stationery: Pen = 8 SAR / 6-pack = 42 SAR (save 6 SAR) / 12-pack = 72 SAR (save 24 SAR) — quantity options with clear buttons.",
    ],
    result: "Showing a progress bar 'Add one more unit and save X SAR' increases the rate of choosing larger quantities by 42% compared to a static tier table — a direct, personal message motivates more.",
  },
  },
  {
    id: "BuyTogether",
    href: "/use-cases/buy-together",
    tagAr: "حسب طريقة العرض",
    titleAr: "الشراء معاً",
    tagEn: "By Display Method",
    titleEn: "Frequently Bought Together",
    scenario: {
    title: "أمثلة تطبيقية من قطاعات متنوعة",
    steps: [
      "☕ قهوة: عميل يشاهد آلة قهوة → يرى طقم 'الشراء معاً': آلة + مطحنة + كبسولات مجموعة — 'عملاء اشتروا هذه الآلة اشتروا أيضاً هذه المجموعة'.",
      "📷 تصوير: عميل يشاهد كاميرا → يُعرض له: كاميرا + حقيبة حمل + بطاقة ذاكرة + بطارية احتياطية كطقم واحد.",
      "💪 رياضة: عميل يشاهد حبل تمرين → طقم مقترح: حبل + قفازات + حصيرة تمرين — بزر 'أضف الطقم كاملاً'.",
      "🧴 عناية: عميلة تشاهد غسول الوجه → طقم البشرة: غسول + تونر + مرطب — 'الروتين الأكثر شراءً معاً لدى عملائنا'.",
    ],
    result: "عرض 'الشراء معاً' بخيار إضافة الكل دفعة واحدة يرفع نسبة تبنّي الطقم الكامل من 9% إلى 33% — كل ثلاثة أفراد من كل عشرة يختارون الطقم بدلاً من قطعة واحدة.",
  },
    scenarioEn: {
    title: "Real examples from various industries",
    steps: [
      "☕ Coffee: Customer views a coffee machine → sees 'Bought Together' set: machine + grinder + capsule collection — 'Customers who bought this machine also bought this set'.",
      "📷 Photography: Customer views a camera → shown: camera + carrying bag + memory card + spare battery as one set.",
      "💪 Fitness: Customer views a resistance band → suggested set: band + gloves + exercise mat — with an 'Add Complete Set' button.",
      "🧴 Skincare: Customer views face wash → skincare set: wash + toner + moisturizer — 'The most popular routine bought together by our customers'.",
    ],
    result: "Showing 'Bought Together' with a one-click add-all option increases complete set adoption from 9% to 33% — three out of every ten customers choose the set instead of a single item.",
  },
  },
  {
    id: "CartPage",
    href: "/use-cases/cart",
    tagAr: "حسب الصفحات",
    titleAr: "صفحة السلة",
    tagEn: "By Pages",
    titleEn: "Cart Page",
    scenario: {
    title: "عميل في سلة بقيمة 170 ⃁",
    steps: [
      "العميل أضاف منتجي تجميل بقيمة 170 ⃁.",
      "يكتشف زيادة أن عتبة الشحن المجاني عند 200 ⃁ — الفجوة 30 ⃁ فقط.",
      "يظهر مباشرة: 'أضف 30 ⃁ وتحصل على شحن مجاني' + بلسم شعر بـ 32 ⃁ كاقتراح.",
      "العميل يضيف البلسم برضا لأن التوفير محسوس ومباشر.",
    ],
    result: "الطلب ارتفع من 170 إلى 202 ⃁ والعميل شعر أنه هو من استفاد من الصفقة.",
  },
    scenarioEn: {
    title: "A customer with a 170 SAR cart",
    steps: [
      "The customer added two beauty products worth 170 SAR.",
      "Ziadah discovers the free shipping threshold is 200 SAR — the gap is only 30 SAR.",
      "Instantly shows: 'Add 30 SAR to get free shipping' + a hair conditioner at 32 SAR as a suggestion.",
      "The customer adds the conditioner happily because the savings feel tangible and direct.",
    ],
    result: "The order rose from 170 to 202 SAR and the customer felt they benefited from the deal.",
  },
  },
  {
    id: "CategoryPage",
    href: "/use-cases/category",
    tagAr: "حسب الصفحات",
    titleAr: "صفحة التصنيف",
    tagEn: "By Pages",
    titleEn: "Category Page",
    scenario: {
    title: "عميل يتصفح تصنيف 'أجهزة الصوت'",
    steps: [
      "يفتح العميل تصنيف أجهزة الصوت ويرى 40 منتجاً.",
      "زيادة يعرف من تاريخه أنه مهتم بالجودة وعنده ميزانية متوسطة (سبق أن اشترى منتجات بين 300-600 ⃁).",
      "يُعيد ترتيب المنتجات: السماعات في نطاق ميزانيته تظهر أولاً، مع شارة 'الأكثر مبيعاً هذا الأسبوع' على أحدها.",
      "يظهر بطاقة كومبو: 'سماعة + حامل + كابل شحن بخصم 15%'.",
    ],
    result: "العميل وجد ما يريده في أقل من دقيقتين وأضاف الكومبو للسلة مباشرة.",
  },
    scenarioEn: {
    title: "A customer browsing the 'Audio Devices' category",
    steps: [
      "The customer opens the audio devices category and sees 40 products.",
      "Ziadah knows from their history they're interested in quality and have a mid-range budget (previously bought products between 300-600 SAR).",
      "It reorders products: speakers within their budget appear first, with a 'Best Seller This Week' badge on one.",
      "A combo card appears: 'Speaker + stand + charging cable at 15% off'.",
    ],
    result: "The customer found what they wanted in under two minutes and added the combo to cart directly.",
  },
  },
  {
    id: "CheckoutPage",
    href: "/use-cases/checkout",
    tagAr: "حسب الصفحات",
    titleAr: "صفحة الدفع",
    tagEn: "By Pages",
    titleEn: "Checkout Page",
    scenario: {
    title: "عميل عند الدفع بطلب قيمته 55 ⃁",
    steps: [
      "العميل في صفحة الدفع بطلب بقيمة 55 ⃁ وعتبة الشحن المجاني 200 ⃁.",
      "يكتشف زيادة أن الفجوة 145 ⃁ — ويعرض شريط 'أكمل للشحن المجاني' مع منتجات مقترحة.",
      "يظهر منتجان بسعر 45 و100 ⃁ معاً — مجموعهما 145 ⃁ بالضبط — مع خانة اختيار سهلة.",
      "العميل يضيف المنتجين بنقرتين ويحصل على شحن مجاني كمكافأة.",
    ],
    result: "الطلب ارتفع من 55 إلى 200 ⃁ والعميل شعر أن القرار كان لصالحه — لأنه وفّر تكلفة الشحن.",
  },
    scenarioEn: {
    title: "Customer at checkout with a 55 SAR order",
    steps: [
      "The customer is on the checkout page with a 55 SAR order and a 200 SAR free shipping threshold.",
      "Ziadah discovers the gap is 145 SAR — shows a 'Complete for Free Shipping' bar with suggested products.",
      "Two products appear at 45 and 100 SAR — totaling exactly 145 SAR — with easy checkboxes.",
      "The customer adds both products with two clicks and gets free shipping as a reward.",
    ],
    result: "The order rose from 55 to 200 SAR and the customer felt the decision was in their favor — because they saved shipping costs.",
  },
  },
  {
    id: "CrossSell",
    href: "/use-cases/cross-sell",
    tagAr: "حسب الأنشطة",
    titleAr: "البيع المتقاطع",
    tagEn: "By Activity",
    titleEn: "Cross-Selling",
    scenario: {
    title: "أمثلة تطبيقية من قطاعات مختلفة",
    steps: [
      "🍕 مطعم: عميل اشترى برغر → يُقترح له بطاطس + مشروب + صلصة إضافية (كومبو وجبة كاملة).",
      "💄 تجميل: عميلة اشترت فاونديشن → يُقترح لها برايمر + بودرة تثبيت + إسفنجة تطبيق.",
      "💻 إلكترونيات: عميل اشترى لابتوب → يُقترح له حقيبة + ماوس لاسلكي + منصة تبريد.",
      "👕 أزياء: عميل اشترى قميص → يُقترح له بنطلون مكمّل + حزام بنفس اللون.",
    ],
    result: "في جميع هذه الأمثلة، معدل قبول الاقتراح المتقاطع بين 25 و45% — كل قبول واحد يساوي طلباً إضافياً بدون تكلفة تسويق.",
  },
    scenarioEn: {
    title: "Real examples from different industries",
    steps: [
      "🍕 Restaurant: Customer bought a burger → suggested: fries + drink + extra sauce (complete meal combo).",
      "💄 Beauty: Customer bought foundation → suggested: primer + setting powder + application sponge.",
      "💻 Electronics: Customer bought a laptop → suggested: bag + wireless mouse + cooling pad.",
      "👕 Fashion: Customer bought a shirt → suggested: matching pants + belt in the same color.",
    ],
    result: "In all these examples, the cross-sell acceptance rate ranges from 25-45% — each acceptance equals an extra order without marketing cost.",
  },
  },
  {
    id: "CustomerExperience",
    href: "/use-cases/customer-experience",
    tagAr: "تجربة العميل",
    titleAr: "تخصيص التجربة",
    tagEn: "Customer experience",
    titleEn: "Personalized experience",
    scenario: {
    title: "نورة وناصر في نفس المتجر — تجربتان مختلفتان تماماً",
    steps: [
      "نورة دخلت من إعلان رمضان على تجميل: المحرك يرفع أوزان العطور والهدايا الموسمية ويخفّض إلكترونيات الرياضة.",
      "تمرّرت طويلاً على كريمات البشرة وكبّرت صورة طقم عناية — تُسجَّل كإشارات نية قوية قبل الشراء.",
      "ناصر زار من بحث عن «آيفون»: يُكتشف نمط تقني رياضي من مشترياته السابقة وساعته القديمة في الملف.",
      "لناصر تظهر إكمالات تقنية ولياقة؛ لنورة تظهر عطور رمضان وبخور يكمّل سلّة العناية — من نفس المحرك، بمنطق مختلف.",
    ],
    result: "في deployments مشابهة: ارتفع متوسط قيمة الطلب بين 18% و34% في أول ستة أسابيع، ووصل معدل التحويل إلى ضعف أو ثلاثة أضعاف في فئات مختارة — دون ساعات إعداد أسبوعية من التاجر.",
  },
    scenarioEn: {
    title: "Noura and Nasser in the same store — two completely different experiences",
    steps: [
      "Noura arrived from a Ramadan beauty ad: the engine raises weights for seasonal perfumes and gifts and de-emphasizes sports electronics.",
      "She lingered on skincare creams and zoomed a care set — logged as strong pre-purchase intent signals.",
      "Nasser came from an iPhone search: a tech-and-fitness pattern is inferred from past purchases and his old watch in the profile.",
      "Nasser sees tech and fitness complements; Noura sees Ramadan scents and incense that complete a care basket — same engine, different logic.",
    ],
    result: "In comparable deployments: AOV rose between 18% and 34% in the first six weeks, and conversion reached 2–3× in selected categories — without weekly manual setup from the merchant.",
  },
  },
  {
    id: "DiscountCoupon",
    href: "/use-cases/discount-coupon",
    tagAr: "حسب الأهداف",
    titleAr: "قسيمة الخصم",
    tagEn: "By Goals",
    titleEn: "Discount Coupon",
    scenario: {
    title: "عميل في السلة منذ دقائق",
    steps: [
      "يكتشف زيادة التردد أو تجاوز زمن بدون إتمام.",
      "يظهر عرض كوبون بخصم واضح ومدة محدودة.",
      "العميل يُطبّق الكود ويُكمل الطلب.",
    ],
    result: "تحويل من تخلي عن السلة إلى إتمام بعرض محدود الوقت.",
  },
    scenarioEn: {
    title: "Customer in cart for several minutes",
    steps: [
      "Ziadah detects hesitation or time without progress.",
      "A coupon appears with a clear discount and limited time.",
      "The customer applies the code and completes checkout.",
    ],
    result: "Turn cart abandonment into completion with a time-bound offer.",
  },
  },
  {
    id: "FreeShippingDisplay",
    href: "/use-cases/free-shipping",
    tagAr: "حسب الأهداف",
    titleAr: "عرض الشحن المجاني",
    tagEn: "By Goals",
    titleEn: "Free Shipping Display",
    scenario: {
    title: "سلة بقيمة 170 ⃁ وعتبة 200 ⃁",
    steps: [
      "يظهر الشريط: 'باقي 30 ⃁ للشحن المجاني'.",
      "يُقترح منتج تكميلي بـ 32 ⃁ قريب من الفجوة.",
      "العميل يضيف ويحصل على شحن مجاني — يرتفع عدد المنتجات والقيمة معاً.",
    ],
    result: "تحويل من تردد إلى إتمام باستخدام عتبة واضحة واقتراح مخصص.",
  },
    scenarioEn: {
    title: "170 SAR cart, 200 SAR threshold",
    steps: [
      "The bar shows: '30 SAR left for free shipping'.",
      "A complementary item at ~32 SAR is suggested near the gap.",
      "The customer adds and gets free shipping — more items and higher value.",
    ],
    result: "Turn hesitation into completion with a clear threshold and a relevant suggestion.",
  },
  },
  {
    id: "HomePage",
    href: "/use-cases/home",
    tagAr: "حسب الصفحات",
    titleAr: "الصفحة الرئيسية",
    tagEn: "By Pages",
    titleEn: "Home Page",
    scenario: {
    title: "عميل يعود لمتجر ملابس رياضية",
    steps: [
      "زار العميل المتجر قبل أسبوع وتصفّح أحذية الجري لكن لم يشترِ.",
      "في عودته اليوم تستقبله الصفحة الرئيسية بقسم مخصص: 'أحذية الجري الأكثر مبيعاً هذا الأسبوع'.",
      "يظهر تحته كومبو: 'حذاء جري + جوارب رياضية + حزام مائي' بخصم 18%.",
      "في الزاوية العلوية: 'عرض ينتهي خلال 3 ساعات' على الحذاء الذي تصفّحه سابقاً.",
    ],
    result: "العميل انتقل مباشرة للمنتج وأتم الشراء مع الكومبو — وقت الشراء انخفض من 12 دقيقة إلى 3 دقائق.",
  },
    scenarioEn: {
    title: "A customer returns to a sportswear store",
    steps: [
      "The customer visited the store a week ago and browsed running shoes but didn't buy.",
      "On returning today, the home page greets them with a custom section: 'Best-selling running shoes this week'.",
      "Below it, a combo appears: 'Running shoes + sports socks + hydration belt' at 18% off.",
      "In the top corner: 'Offer expires in 3 hours' on the shoe they previously browsed.",
    ],
    result: "The customer went directly to the product and completed the purchase with the combo — purchase time dropped from 12 minutes to 3 minutes.",
  },
  },
  {
    id: "IncreaseAOV",
    href: "/use-cases/increase-aov",
    tagAr: "حسب الأهداف",
    titleAr: "زيادة متوسط السلة",
    tagEn: "By Goals",
    titleEn: "Increase Average Order Value",
    scenario: {
    title: "تأثير رفع متوسط السلة بـ 20%",
    steps: [
      "متجر يستقبل 500 طلب شهرياً بمتوسط سلة 250 ⃁ → إيراد 125,000 ⃁.",
      "بعد تفعيل زيادة: متوسط السلة ارتفع إلى 300 ⃁ (+20%).",
      "نفس عدد الطلبات 500، لكن الإيراد أصبح 150,000 ⃁.",
      "الزيادة الشهرية: 25,000 ⃁ إضافية — بدون عميل جديد واحد.",
    ],
    result: "25,000 ⃁ شهرياً = 300,000 ⃁ سنوياً — مجرد تحسين متوسط السلة بـ 20%.",
  },
    scenarioEn: {
    title: "Impact of raising average cart by 20%",
    steps: [
      "A store receives 500 orders/month at an average cart of 250 SAR → revenue: 125,000 SAR.",
      "After activating Ziadah: average cart rose to 300 SAR (+20%).",
      "Same 500 orders, but revenue became 150,000 SAR.",
      "Monthly increase: 25,000 SAR extra — without a single new customer.",
    ],
    result: "25,000 SAR/month = 300,000 SAR/year — just by improving average cart by 20%.",
  },
  },
  {
    id: "IncreaseConversion",
    href: "/use-cases/increase-conversion",
    tagAr: "حسب الأهداف",
    titleAr: "رفع معدل التحويل",
    tagEn: "By Goals",
    titleEn: "Increase Conversion Rate",
    scenario: {
    title: "حساب تأثير رفع CVR بـ 2%",
    steps: [
      "متجر أزياء يستقبل 8,000 زائر شهرياً بمعدل تحويل 2% = 160 طلباً.",
      "بعد تفعيل زيادة: التخصيص وعروض الكوبون الأول ترفع CVR لـ 4%.",
      "نفس 8,000 زائر → 320 طلباً بمتوسط 400 ⃁ = 128,000 ⃁.",
      "الإيراد السابق: 160 × 400 = 64,000 ⃁. الزيادة: 64,000 ⃁ شهرياً.",
    ],
    result: "مضاعفة الإيراد بدون إنفاق ⃁ واحد إضافي على الإعلانات — فقط بتحسين معدل التحويل.",
  },
    scenarioEn: {
    title: "Calculating the impact of raising CVR by 2%",
    steps: [
      "A fashion store receives 8,000 visitors/month at a 2% conversion rate = 160 orders.",
      "After activating Ziadah: personalization and first-order coupons raise CVR to 4%.",
      "Same 8,000 visitors → 320 orders at 400 SAR average = 128,000 SAR.",
      "Previous revenue: 160 × 400 = 64,000 SAR. Increase: 64,000 SAR/month.",
    ],
    result: "Revenue doubled without spending a single extra SAR on ads — just by improving conversion rate.",
  },
  },
  {
    id: "MoreCartItems",
    href: "/use-cases/more-cart-items",
    tagAr: "حسب الأهداف",
    titleAr: "زيادة عدد المنتجات في السلة",
    tagEn: "By Goals",
    titleEn: "More Items in Cart",
    scenario: {
    title: "مثال سريع",
    steps: [
      "عميل يضيف هاتفاً للسلة.",
      "يظهر: غلاف + واقي شاشة بأسعار صغيرة وزر إضافة بسيط.",
      "يقبل العميل إضافة واحدة أو أكثر — يرتفع عدد بنود السلة فوراً.",
    ],
    result: "نفس الطلب يحتوي على منتجات أكثر دون تغيير في عدد الزوار.",
  },
    scenarioEn: {
    title: "Quick example",
    steps: [
      "A customer adds a phone to the cart.",
      "Case + screen protector appear at small prices with one-tap add.",
      "The customer accepts one or more — line items go up immediately.",
    ],
    result: "The same order contains more products without changing visitor count.",
  },
  },
  {
    id: "ProductPage",
    href: "/use-cases/product-page",
    tagAr: "حسب الصفحات",
    titleAr: "صفحة المنتج",
    tagEn: "By Pages",
    titleEn: "Product Page",
    scenario: {
    title: "عميلة تتصفح عطوراً نسائية",
    steps: [
      "تفتح العميلة صفحة عطر نسائي بسعر 220 ⃁.",
      "يحلل زيادة فوراً: هي من جدة، سبق أن اشترت مجموعة عناية، وتتصفح من هاتفها.",
      "يظهر تحت العطر: 'يشترى معاً' → بخاخ الجسم المكمّل + كريم العطر بحزمة 330 ⃁ بدلاً من 380.",
      "يظهر أيضاً نسخة العطر الكبيرة (300 مل) بسعر 310 مع مقارنة واضحة بالتوفير.",
    ],
    result: "العميلة اشترت الحزمة — الطلب ارتفع من 220 إلى 330 ⃁ (+50%) بمجرد اقتراح واحد.",
  },
    scenarioEn: {
    title: "A customer browsing women's perfumes",
    steps: [
      "The customer opens a women's perfume page priced at 220 SAR.",
      "Ziadah instantly analyzes: she's from Jeddah, previously bought a skincare set, and is browsing from her phone.",
      "Below the perfume: 'Bought Together' → matching body spray + perfume cream as a bundle for 330 SAR instead of 380.",
      "The large perfume version (300ml) also appears at 310 SAR with a clear savings comparison.",
    ],
    result: "The customer bought the bundle — the order increased from 220 to 330 SAR (+50%) with just one suggestion.",
  },
  },
  {
    id: "ReduceAbandon",
    href: "/use-cases/reduce-abandon",
    tagAr: "حسب الأهداف",
    titleAr: "تقليل التخلي عن السلة",
    tagEn: "By Goals",
    titleEn: "Reduce Cart Abandonment",
    scenario: {
    title: "كيف يُنقذ زيادة العميل المتردد",
    steps: [
      "عميلة أضافت فستاناً بـ 380 ⃁ للسلة وجلست 4 دقائق دون تقدم.",
      "زيادة يكتشف أن وقت التردد تجاوز الحد — يُشغّل بروتوكول الإنقاذ.",
      "يظهر بنر خفيف: 'متجر حصري لك: خصم 10% لمدة 12 دقيقة فقط'.",
      "العميلة لم تغادر — شريط الشحن يقول 'أضف 20 ⃁ للشحن المجاني' فأضافت إكسسواراً صغيراً.",
    ],
    result: "أتمّت الشراء بقيمة 440 ⃁ بدلاً من التخلي عن 380 ⃁ — استرداد قيمة الطلب وزيادته في نفس الوقت.",
  },
    scenarioEn: {
    title: "How Ziadah rescues a hesitating customer",
    steps: [
      "A customer added a dress for 380 SAR to the cart and sat for 4 minutes without progress.",
      "Ziadah detects the hesitation time exceeded the threshold — triggers the rescue protocol.",
      "A subtle banner appears: 'Exclusive for you: 10% off for the next 12 minutes only'.",
      "The customer didn't leave — the shipping bar says 'Add 20 SAR for free shipping' so she added a small accessory.",
    ],
    result: "She completed the purchase at 440 SAR instead of abandoning 380 SAR — recovering the order value and increasing it at the same time.",
  },
  },
  {
    id: "RelatedProducts",
    href: "/use-cases/related-products",
    tagAr: "حسب طريقة العرض",
    titleAr: "منتجات ذات صلة",
    tagEn: "By Display Method",
    titleEn: "Related Products",
    scenario: {
    title: "أمثلة تطبيقية من قطاعات مختلفة",
    steps: [
      "🍔 مطعم: عميل يشاهد طبق برغر → تظهر له منتجات ذات صلة: بطاطس، مشروب، صلصة إضافية — كل واحدة بزر إضافة مستقل.",
      "💄 تجميل: عميلة تشاهد كريم ترطيب → تظهر لها: غسول منسجم + سيروم مكمل + كريم عيون — بزر أضف لكل منتج.",
      "💻 إلكترونيات: عميل يشاهد سماعة → يرى: كيس حمل + وصلة بلوتوث + بطارية محمولة — بزر إضافة سريع.",
      "👟 أزياء: عميل يشاهد حذاء رياضي → تُعرض له: جوارب مناسبة + كيس رياضي + ربطات بديل — يضيف ما يشاء فورياً.",
    ],
    result: "متوسط قبول اقتراح 'منتجات ذات صلة' يبلغ 38% عند استخدام زر الإضافة المباشر مقابل 16% عند الاكتفاء بالرابط — الفارق في التصميم يصنع الفارق في الإيراد.",
  },
    scenarioEn: {
    title: "Real examples from different industries",
    steps: [
      "🍔 Restaurant: Customer views a burger → related products appear: fries, drink, extra sauce — each with an independent add button.",
      "💄 Beauty: Customer views a moisturizer → shown: matching cleanser + complementary serum + eye cream — with an add button for each.",
      "💻 Electronics: Customer views headphones → sees: carrying case + Bluetooth adapter + portable battery — with a quick add button.",
      "👟 Fashion: Customer views running shoes → shown: matching socks + gym bag + replacement laces — they add what they want instantly.",
    ],
    result: "Average acceptance of 'Related Products' suggestions reaches 38% with a direct add button vs. 16% with links only — the design difference makes the revenue difference.",
  },
  },
  {
    id: "RemoveFromCartPage",
    href: "/use-cases/remove-from-cart",
    tagAr: "حسب الأنشطة",
    titleAr: "الحذف من السلة",
    tagEn: "By Activity",
    titleEn: "Remove from Cart",
    scenario: {
    title: "عميل أراد حذف حذاء رياضي",
    steps: [
      "أضاف العميل حذاء رياضي بـ 280 ⃁ لكنه تردد وضغط 'حذف'.",
      "رصد زيادة المحاولة فوراً وعرض: 'قبل أن تحذفه — خصم 15% خاص لك الآن: السعر 238 ⃁ لمدة 9 دقائق فقط'.",
      "ظهر العرض بتصميم واضح مع عداد تنازلي يُشعر العميل بالحاجة للقرار الفوري.",
      "العميل اختار الاستفادة من الخصم وأتمّ الشراء بدلاً من الحذف.",
    ],
    result: "بيع بـ 238 ⃁ بدلاً من خسارة 280 ⃁ كاملاً — المتجر احتفظ بالعميل وحقق إيراداً لم يكن ليحدث لولا التدخل الذكي.",
  },
    scenarioEn: {
    title: "A customer wanted to remove a running shoe",
    steps: [
      "The customer added running shoes at 280 SAR but hesitated and clicked 'Remove'.",
      "Ziadah detected the attempt instantly and showed: 'Before you remove — 15% special discount for you now: 238 SAR for 9 minutes only'.",
      "The offer appeared with a clear design and a countdown timer creating a sense of urgency for an immediate decision.",
      "The customer chose to take advantage of the discount and completed the purchase instead of removing.",
    ],
    result: "A sale at 238 SAR instead of losing 280 SAR entirely — the store retained the customer and earned revenue that wouldn't have happened without smart intervention.",
  },
  },
  {
    id: "ThankYouPage",
    href: "/use-cases/thank-you",
    tagAr: "حسب الصفحات",
    titleAr: "صفحة الشكر",
    tagEn: "By Pages",
    titleEn: "Thank You Page",
    scenario: {
    title: "عميل اشترى هاتفاً جديداً",
    steps: [
      "العميل أتم شراء هاتف Galaxy بسعر 1800 ⃁.",
      "تظهر له صفحة شكر مخصصة من زيادة بدلاً من الصفحة الجامدة المعتادة.",
      "يظهر له: 'عملاء اشتروا هذا الهاتف أضافوا أيضاً → واقي شاشة + غلاف + سماعة بلوتوث بحزمة 280 ⃁'.",
      "يظهر أيضاً كوبون 15% خصم لأي طلب خلال 48 ساعة القادمة.",
    ],
    result: "38% من هؤلاء العملاء أضافوا الإكسسوارات فوراً، و22% عادوا خلال 48 ساعة باستخدام الكوبون.",
  },
    scenarioEn: {
    title: "A customer who bought a new phone",
    steps: [
      "The customer completed a Galaxy phone purchase at 1,800 SAR.",
      "A personalized thank you page from Ziadah appears instead of the usual static page.",
      "Shown: 'Customers who bought this phone also added → screen protector + case + Bluetooth earbuds as a bundle for 280 SAR'.",
      "Also shown: a 15% coupon for any order within the next 48 hours.",
    ],
    result: "38% of these customers added accessories immediately, and 22% returned within 48 hours using the coupon.",
  },
  },
  {
    id: "Upsell",
    href: "/use-cases/upsell",
    tagAr: "حسب الأهداف",
    titleAr: "استبدال المنتجات",
    tagEn: "By Goals",
    titleEn: "Product Swap",
    scenario: {
    title: "أمثلة تطبيقية حقيقية عبر قطاعات",
    steps: [
      "🎧 إلكترونيات: عميل ينظر لسماعة بـ 120 ⃁ → يرى عرض 'سماعة بـ 190 ⃁ — عزل صوت فعّال + 20 ساعة بطارية + ضمان سنتان' مع مقارنة مباشرة.",
      "💐 عطور: عميلة تنظر لعطر 30 مل → تجد 'النسخة 100 مل بـ 310 ⃁ (توفر 35% في سعر الـ مل)'.",
      "🌿 عناية: عميل اختار كريم أساسي → يظهر كريم بريميوم بنفس الوزن وبـ 30 ⃁ إضافية مع قائمة مكونات نشطة أكثر.",
      "📚 كورسات: مشترك في باقة أساسية → يرى ترقية للباقة المتقدمة بفارق 80 ⃁ مع 3 كورسات إضافية وشهادة.",
    ],
    result: "معدل قبول عرض الترقية يتراوح بين 22 و35% عند تقديمه بالطريقة الصحيحة مع إبراز القيمة — وكل قبول يرفع الإيراد مباشرة.",
  },
    scenarioEn: {
    title: "Real examples across industries",
    steps: [
      "🎧 Electronics: Customer views headphones at 120 SAR → sees 'Headphones at 190 SAR — active noise cancellation + 20-hour battery + 2-year warranty' with a direct comparison.",
      "💐 Perfumes: Customer views 30ml perfume → finds '100ml version for 310 SAR (saving 35% per ml)'.",
      "🌿 Skincare: Customer chose a basic cream → premium cream appears, same weight but 30 SAR more with a list of more active ingredients.",
      "📚 Courses: Subscriber on basic plan → sees upgrade to advanced plan for 80 SAR more with 3 extra courses and a certificate.",
    ],
    result: "Upgrade acceptance rate ranges from 22-35% when presented correctly with value emphasis — and each acceptance directly increases revenue.",
  },
  }
];
