/**
 * Self-host the webfonts that were previously loaded from Google Fonts.
 *
 * Fetches the same css2 stylesheets Google serves (so glyphs/hinting are
 * identical), downloads every referenced woff2 into public/fonts/, rewrites the
 * src URLs to local /fonts/ paths, and writes a combined src/fonts.css with
 * font-display: swap. Run once to (re)generate assets:
 *
 *   node scripts/fetch-fonts.mjs
 *
 * Then index.css imports ./fonts.css instead of the remote @import URLs.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const FONT_DIR = path.join(ROOT, "public", "fonts");
const OUT_CSS = path.join(ROOT, "src", "fonts.css");

// Same family/weight specs that were in index.css's remote @import lines.
const SHEETS = [
  "https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@300;400;500;600;700&family=Inter:wght@400;500;600;700;800&display=swap",
  "https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap",
  "https://fonts.googleapis.com/css2?family=Tajawal:wght@400;500;600;700;800&display=swap",
  "https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;1,400;1,500&display=swap",
];

const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36";

async function main() {
  fs.mkdirSync(FONT_DIR, { recursive: true });
  const seen = new Map(); // gstatic url -> local filename
  let css = `/* Self-hosted fonts — generated by scripts/fetch-fonts.mjs. Do not edit by hand. */\n`;

  for (const sheet of SHEETS) {
    const res = await fetch(sheet, { headers: { "User-Agent": UA } });
    if (!res.ok) throw new Error(`Failed to fetch ${sheet}: ${res.status}`);
    let block = await res.text();

    const urls = [...block.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/g)].map((m) => m[1]);
    for (const url of urls) {
      if (!seen.has(url)) {
        const base = url.split("/").slice(-2).join("-"); // e.g. v12-Iura6YBj...woff2
        const fname = base.replace(/[^a-zA-Z0-9._-]/g, "");
        const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
        fs.writeFileSync(path.join(FONT_DIR, fname), buf);
        seen.set(url, fname);
      }
      block = block.split(url).join(`/fonts/${seen.get(url)}`);
    }
    css += `\n/* ${sheet.match(/family=([^&]+)/)?.[1] ?? ""} */\n${block.trim()}\n`;
  }

  fs.writeFileSync(OUT_CSS, css, "utf8");
  console.log(`[fonts] downloaded ${seen.size} woff2 files -> public/fonts/, wrote src/fonts.css`);
}

main().catch((err) => {
  console.error(`[fonts] error: ${err.message}`);
  process.exit(1);
});
