/**
 * Generates public/sitemap.xml from blog posts, sectors, support articles, and static routes.
 * Run before `vite build` so crawlers see every indexable URL + hreflang alternates.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const SITE = "https://www.ziadah.app";
const OUT = path.join(ROOT, "public", "sitemap.xml");

function readUtf8(rel) {
  return fs.readFileSync(path.join(ROOT, rel), "utf8");
}

/** @returns {{ slug: string, lastmod: string }[]} */
function parseBlogPosts() {
  const raw = readUtf8("src/data/blogPosts.ts");
  const posts = [];
  const re =
    /^\s+slug:\s*"([^"]+)"\s*,\s*$/gm;
  let m;
  while ((m = re.exec(raw)) !== null) {
    const slug = m[1];
    if (slug === "string") continue;
    const start = m.index;
    const chunk = raw.slice(start, start + 4000);
    const dm = chunk.match(/publishDateIso:\s*"([^"]+)"/);
    const lastmod = dm ? dm[1] : new Date().toISOString().slice(0, 10);
    posts.push({ slug, lastmod });
  }
  return posts;
}

function parseSectorSlugs() {
  const raw = readUtf8("src/data/sectors.ts");
  const slugs = [];
  const re = /^\s+slug:\s*"([^"]+)"\s*,\s*$/gm;
  let m;
  while ((m = re.exec(raw)) !== null) {
    if (m[1] === "string") continue;
    slugs.push(m[1]);
  }
  return slugs;
}

function parseSupportArticleIds() {
  const raw = readUtf8("src/data/support-data.ts");
  const ids = [];
  const re = /id:\s*"([^"]+)"\s*,\s*\n\s*categoryId:/g;
  let m;
  while ((m = re.exec(raw)) !== null) {
    ids.push(m[1]);
  }
  return ids;
}

function esc(s) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function urlEntry(loc, locAr, locEn, lastmod, changefreq, priority) {
  return `  <url>
    <loc>${esc(loc)}</loc>
    <xhtml:link rel="alternate" hreflang="ar" href="${esc(locAr)}" />
    <xhtml:link rel="alternate" hreflang="en" href="${esc(locEn)}" />
    <xhtml:link rel="alternate" hreflang="x-default" href="${esc(SITE + "/")}" />
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
}

const USE_CASE_PATHS = [
  "/use-cases/product-page",
  "/use-cases/cart",
  "/use-cases/thank-you",
  "/use-cases/home",
  "/use-cases/category",
  "/use-cases/all-pages",
  "/use-cases/cross-sell",
  "/use-cases/upsell",
  "/use-cases/increase-aov",
  "/use-cases/reduce-abandon",
  "/use-cases/increase-conversion",
  "/use-cases/related-products",
  "/use-cases/addons",
  "/use-cases/buy-together",
  "/use-cases/bundle-deals",
  "/use-cases/buy-more-save-more",
  "/use-cases/checkout",
  "/use-cases/add-to-cart",
  "/use-cases/remove-from-cart",
  "/use-cases/customer-experience",
  "/use-cases/more-cart-items",
  "/use-cases/free-shipping",
  "/use-cases/discount-coupon",
  "/use-cases/by-pages",
  "/use-cases/by-activity",
  "/use-cases/by-presentation",
  "/use-cases/by-goal",
  "/use-cases/by-experience",
];

const STATIC_MAIN = [
  { path: "/", priority: "1.0", freq: "weekly" },
  { path: "/features", priority: "0.9", freq: "monthly" },
  { path: "/calculator", priority: "0.85", freq: "monthly" },
  { path: "/analyze", priority: "0.88", freq: "weekly" },
  { path: "/success-stories", priority: "0.85", freq: "monthly" },
  { path: "/blog", priority: "0.9", freq: "weekly" },
  { path: "/support", priority: "0.75", freq: "monthly" },
  { path: "/privacy", priority: "0.3", freq: "yearly" },
  { path: "/terms", priority: "0.3", freq: "yearly" },
  { path: "/sectors", priority: "0.85", freq: "weekly" },
  { path: "/sectors/ecommerce-stores", priority: "0.85", freq: "weekly" },
  { path: "/zid-apps-comparison", priority: "0.75", freq: "monthly" },
];

function main() {
  const blogPosts = parseBlogPosts();
  const sectorSlugs = parseSectorSlugs();
  const supportIds = parseSupportArticleIds();
  const today = new Date().toISOString().slice(0, 10);

  const parts = [];
  parts.push(`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand -->
`);

  /** @param {string} pathNoHost path like / or /blog/foo */
  function emitPair(pathNoHost, lastmod, freq, priority) {
    const locAr = pathNoHost === "/" ? `${SITE}/` : `${SITE}${pathNoHost}`;
    const locEn = pathNoHost === "/" ? `${SITE}/en` : `${SITE}/en${pathNoHost}`;
    parts.push(urlEntry(locAr, locAr, locEn, lastmod, freq, priority));
    parts.push(urlEntry(locEn, locAr, locEn, lastmod, freq, priority));
  }

  for (const s of STATIC_MAIN) {
    emitPair(s.path, today, s.freq, s.priority);
  }

  for (const slug of sectorSlugs) {
    emitPair(`/sectors/${slug}`, today, "weekly", "0.8");
  }

  for (const p of USE_CASE_PATHS) {
    emitPair(p, today, "monthly", "0.65");
  }

  for (const id of supportIds) {
    emitPair(`/support/article/${id}`, today, "monthly", "0.55");
  }

  for (const { slug, lastmod } of blogPosts) {
    emitPair(`/blog/${slug}`, lastmod, "monthly", "0.72");
  }

  parts.push(`</urlset>
`);

  fs.writeFileSync(OUT, parts.join("\n"), "utf8");
  console.log(
    `sitemap: wrote ${OUT} (${blogPosts.length} blog posts, ${sectorSlugs.length} sectors, ${supportIds.length} support articles)`
  );
}

main();
